server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: slave1
eureka:
  instance:
    hostname: slave1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/,http://slave3:8763/eureka/
---
server:
  port: 8762
spring:
  application:
    name: eureka-server
  profiles: slave2
eureka:
  instance:
    hostname: slave2
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/,http://slave3:8763/eureka/
---
server:
  port: 8763
spring:
  application:
    name: eureka-server
  profiles: slave3
eureka:
  instance:
    hostname: slave3
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/,http://slave1:8761/eureka/